name: CIRCT Build for ARM64

on:
  push:
    branches:
      - build-aarch64

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            python3 \
            python3-pip \
            clang \
            lld \
            llvm-dev \
            libclang-dev

    - name: Clone CIRCT and submodules
      run: |
        git clone https://github.com/llvm/circt.git
        cd circt
        git checkout firtool-1.85
        git submodule init
        git submodule update
        cd llvm
        git fetch --unshallow

    - name: Build LLVM/MLIR
      run: |
        mkdir -p circt/llvm/build
        cd circt/llvm/build
        cmake -G Ninja ../llvm \
            -DLLVM_ENABLE_PROJECTS="mlir" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE=DEBUG \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        ninja
        ninja check-mlir

    - name: Build CIRCT
      run: |
        mkdir -p circt/build
        cd circt/build
        cmake -G Ninja .. \
            -DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
            -DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE=DEBUG \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        ninja
        ninja check-circt
        ninja check-circt-integration

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: circt-build
        path: circt/build/
